import Head from 'next/head'
import Landing from '../components/layout/Landing'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bustabit Analayze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </div>
  )
}
